services:
  budget-app:
    build: .
    ports:
      - "8080:8080"  # Основное приложение
      - "8081:8081"  # Telegram бот
    environment:
      # Основное приложение использует локальную БД на хосте
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/budget_app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=765338955Lulu
      # Telegram бот
      - TELEGRAM_BOT_TOKEN=7965126137:AAG-vCrB_jdDm2tvgRgeKVKAQ_kR9ueDRqQ
      - TELEGRAM_BOT_USERNAME=theBestBudget_bot
      - MAIN_APP_WS_URL=ws://budget-app:8080/ws