[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:main-app]
command=java -Dspring.profiles.active=docker -jar /app/main-app.jar
directory=/app
autostart=true
autorestart=true
stderr_logfile=/tmp/main-app.err.log
stdout_logfile=/tmp/main-app.out.log

[program:telegram-bot]
command=java -Dspring.profiles.active=telegram -jar /app/telegram-bot.jar
directory=/app
autostart=true
autorestart=true
stderr_logfile=/tmp/telegram-bot.err.log
stdout_logfile=/tmp/telegram-bot.out.log